# Generated by Django 4.2.2 on 2023-07-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_tb_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_registration',
            name='login_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_login'),
            preserve_default=False,
        ),
    ]
