# Generated by Django 4.2.2 on 2023-07-19 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_tb_shop_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_shop_registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_login')),
            ],
        ),
        migrations.DeleteModel(
            name='tb_shop_registration',
        ),
    ]
