# Generated by Django 4.2.2 on 2023-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_tb_shop_registrations_delete_tb_shop_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
    ]
