# Generated by Django 4.2.2 on 2023-07-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_tb_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('est_year', models.CharField(max_length=100)),
            ],
        ),
    ]
