# Generated by Django 4.2.2 on 2023-07-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_tb_vendors'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_product_category')),
                ('shop_registrations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_shop_registrations')),
                ('vendors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_vendors')),
            ],
        ),
    ]
