# Generated by Django 4.2.2 on 2023-07-21 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_tb_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=20)),
                ('date_time', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_product')),
            ],
        ),
    ]
