# Generated by Django 4.2.2 on 2023-07-21 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_tb_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=20)),
                ('review', models.CharField(max_length=200)),
                ('date_time', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_registration')),
            ],
        ),
        migrations.CreateModel(
            name='tb_order_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('shop_registrations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_shop_registrations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_registration')),
            ],
        ),
        migrations.CreateModel(
            name='tb_order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('order_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_order_master')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_product')),
            ],
        ),
    ]
