# Generated by Django 4.2.2 on 2023-07-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_tb_rating_tb_order_master_tb_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_product',
            name='vendors',
        ),
    ]
