# Generated by Django 4.2.2 on 2023-07-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_remove_tb_product_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_product',
            name='stocks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_stocks'),
            preserve_default=False,
        ),
    ]
