# Generated by Django 4.2.2 on 2023-07-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_tb_product_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_product',
            name='stocks',
            field=models.CharField(max_length=20),
        ),
    ]
